version: "3.8"

services:
  mysql_db:
    image: mysql:5.7
    env_file:
      - .env
    environment:
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    restart: always
    container_name: ${MYSQL_CONTAINER_NAME}
    volumes:
      - db_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d/

  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    volumes:
      - .:/sql_alchemy
    env_file:
      - .env
    depends_on:
      - mysql_db
    container_name: flask_app_b

volumes:
  db_data:
