version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    command: bash -c "./setup.sh"
    volumes:
      - .:/app
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://root@db/miniblog
      - JWT_SECRET_KEY=clave-jwt

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=your_db_root_password
      - MYSQL_DATABASE=miniblog
      - MYSQL_USER=root
    volumes:
      - ./db_data:/var/lib/mysql
